### ISSUE TITLE
Problem with Maven

### ISSUE THREAD

**Issue by Eduardo-Ortega102** [skinny85/specnaz#14]
Hi!

the repository section in your maven example is not working, you need to replace **http** by **https**

Have a nice day! :)

**Comment by skinny85** [comment]
Hey @Eduardo-Ortega102 ,

Thanks a lot for noticing the issue!

Any chance you would submit a quick PR to fix this? 😄 

Thanks,
Adam

**Comment by Eduardo-Ortega102** [comment]
@skinny85 done! 😁

**Comment by skinny85** [comment]
> @skinny85 done! 😁

Thanks so much!
